"""Test isolation. The dev `.env` may configure a live AI provider (EXPLAIN_PROVIDER=openai + a key);
tests must never depend on it or hit the network. This autouse fixture forces the deterministic
'template' provider and clears provider keys for every test. Tests that exercise a provider set it
explicitly AND mock the transport (see test_llm.py)."""
import json
import pathlib
from datetime import UTC, date, datetime

import pytest


@pytest.fixture(autouse=True)
def _isolate_ai_provider(monkeypatch):
    monkeypatch.setenv("EXPLAIN_PROVIDER", "template")
    for key in ("OPENAI_API_KEY", "OPENAI_BASE_URL", "OPENAI_MODEL", "GEMINI_API_KEY"):
        monkeypatch.delenv(key, raising=False)


# ------------------------------------------------------------------ deterministic prices
#
# WHY THE SCORING TESTS DO NOT READ `prices_eod`.
#
# They used to build their fixtures out of whatever the live table happened to hold — `real =
# scoring._series; spy = real(conn, "SPY")` — and then slice it. That quietly made eight tests
# depend on three things none of them is about: an Alpaca key, how much history had been ingested,
# and today's date. On a fresh clone `make quickstart` loads one month of closes, a call published
# 200 days ago has no entry session inside it, and all eight failed with `verdict is None` on a
# scorer that was working perfectly.
#
# The fixture is committed, generated by a closed form recorded inside the file, and dated in the
# PAST rather than relative to `today`, so the same bytes produce the same verdict forever. It is
# not vendor data, so the redistribution rule that keeps real closes off every screen in this
# product does not reach it.

_SYNTHETIC = pathlib.Path(__file__).parent / "fixtures" / "prices_synthetic.json"

# A publication date well inside the fixture's range, with room for a 30-day horizon to close and
# for 90 days of history behind it. Fixed, not derived from `now()`.
SYNTHETIC_PUBLISHED_AT = datetime(2024, 9, 3, 14, 30, tzinfo=UTC)


class SyntheticMarket:
    """The committed price series, and the hooks that make the product read them.

    `use_subject` exists because several tests are about a DAMAGED series — one that stops early,
    one with holes punched in it — and the honest way to test that is to hand the scorer the broken
    shape rather than to hope the live table is currently broken in the right way.
    """

    def __init__(self, sessions, closes, monkeypatch):
        from tradeos.backtest.engine import Series
        self._Series = Series
        self.sessions = sessions
        self._all = {sym: Series(list(sessions), dict(zip(sessions, vals, strict=True)))
                     for sym, vals in closes.items()}
        self.spy = self._all["SPY"]
        self.symbol = "ABT"
        self.subject = self._all[self.symbol]
        self.published_at = SYNTHETIC_PUBLISHED_AT
        self._mp = monkeypatch
        self._apply()

    def series_of(self, days):
        """A Series over a subset of the benchmark's sessions, carrying the subject's closes."""
        return self._Series(list(days), {d: self.subject.close[d] for d in days})

    def use_subject(self, series):
        self._all[self.symbol] = series
        self.subject_override = series
        self._apply()

    def _apply(self):
        from tradeos.receipts import calls as calls_mod
        from tradeos.receipts import scoring as scoring_mod
        empty = self._Series([], {})
        table = self._all

        def _series(_conn, symbol):
            return table.get((symbol or "").upper(), empty)

        def _last_close(_conn, symbol):
            s = table.get((symbol or "").upper(), empty)
            return (s.days[-1], len(s.days)) if s.days else (None, 0)

        self._mp.setattr(scoring_mod, "_series", _series)
        self._mp.setattr(calls_mod, "_last_close", _last_close)


@pytest.fixture
def synthetic_market(monkeypatch):
    doc = json.loads(_SYNTHETIC.read_text(encoding="utf-8"))
    sessions = [date.fromisoformat(s) for s in doc["sessions"]]
    return SyntheticMarket(sessions, doc["closes"], monkeypatch)
