// Radar — the app's main screen.
//
// One continuously-updating stream of what matters, ranked by relevance to you. The rule that
// shapes every card: LEAD WITH THE CONSEQUENCE, not the headline. A reader came here to find out
// what something means for them; the headline is provenance, not the answer. So the mechanism is
// the largest text on the card and the source article is a link underneath it.
//
// Everything else follows from honesty commitments made elsewhere in the codebase:
//   * confidence is always visible, never stripped from a call;
//   * `contradicts` is surfaced, not smoothed away — two live interpretations disagreeing is
//     more useful than one confident narrative;
//   * every card says why IT is in front of you, because an unexplained ranking is
//     indistinguishable from an arbitrary one.
import { useEffect, useMemo, useState } from "react";
import { fetchClaims, fetchCountries, saveProfileFrame } from "./api";
import { Icon } from "./icons.jsx";
import { EmptyState, LoadError } from "./shell.jsx";

const DIR = { up: "▲", down: "▼" };
const pct = (v) => `${Math.round((v || 0) * 100)}%`;

const ago = (iso) => {
  const mins = Math.round((Date.now() - new Date(iso).getTime()) / 60000);
  if (mins < 1) return "just now";
  if (mins < 60) return `${mins}m ago`;
  if (mins < 1440) return `${Math.round(mins / 60)}h ago`;
  return `${Math.round(mins / 1440)}d ago`;
};

const confBand = (c) => (c >= 0.7 ? "high" : c >= 0.4 ? "medium" : "low");

function Affected({ items }) {
  if (!items?.length) return null;
  return (
    <div className="rd-affected">
      {items.map((a, i) => (
        <span key={i} className={`rd-chip dir-${a.direction}`} title={`${a.kind} · ${a.magnitude}`}>
          <b>{DIR[a.direction] || "•"}</b> {a.value}
          <em>{a.magnitude}</em>
        </span>
      ))}
    </div>
  );
}

function Card({ c, onOpenClaim }) {
  const [open, setOpen] = useState(false);
  return (
    <article className="rd-card">
      <div className="rd-top">
        <span className={`rd-conf band-${confBand(c.confidence)}`} title="stated confidence; scored later in the Ledger">
          {pct(c.confidence)}
        </span>
        <span className="rd-cat">{c.category || "event"}</span>
        {(c.geo || []).map((g) => <span key={g} className="rd-geo">{g}</span>)}
        <span className="rd-horizon">over {c.horizon}</span>
        <span className="spacer" />
        <span className="rd-when">{ago(c.created_at)}</span>
      </div>

      {/* The consequence, first and largest. This is what the reader came for. */}
      <p className="rd-mechanism">{c.mechanism}</p>

      <Affected items={c.affected} />

      {c.contradicts?.length > 0 && (
        <div className="rd-contra" title="two live interpretations disagree">
          <Icon name="alert" size={13} /> {c.contradicts.length} live interpretation
          {c.contradicts.length === 1 ? "" : "s"} disagree{c.contradicts.length === 1 ? "s" : ""} with this
        </div>
      )}

      <div className="rd-foot">
        {c.url
          ? <a className="rd-src" href={c.url} target="_blank" rel="noreferrer noopener">{c.source} ↗</a>
          : <span className="rd-src">{c.source}</span>}
        <span className="rd-why">{c.why_shown}</span>
        <span className="spacer" />
        <button className="linkish" onClick={() => setOpen((o) => !o)}>
          {open ? "hide reasoning" : "show reasoning"}
        </button>
      </div>

      {open && (
        <div className="rd-reasoning">
          {c.headline && <div className="rd-headline">Reported as: “{c.headline}”</div>}
          {c.reasoning_trace?.length > 0 && (
            <ol className="rd-chain">{c.reasoning_trace.map((r, i) => <li key={i}>{r}</li>)}</ol>
          )}
          {c.analogs?.length > 0 && (
            <div className="rd-analogs">
              <div className="an-title">When something like this happened before</div>
              {c.analogs.map((a, i) => (
                <div key={i} className="rd-analog">
                  <b>{a.when}</b> {a.what}
                  {a.what_followed && <span className="rd-followed"> → {a.what_followed}</span>}
                </div>
              ))}
            </div>
          )}
          <div className="rd-parts">
            {Object.entries(c.parts || {}).map(([k, v]) => (
              <span key={k} className="rd-part">{k} {v}</span>
            ))}
          </div>
          <div className="an-foot">
            Generated by {c.model_version}. Scored in the Ledger once its {c.horizon} horizon
            elapses{c.status === "open" ? " (still open)" : ""}.
          </div>
        </div>
      )}
    </article>
  );
}

/** Setting a country is what turns a generic feed into a personal one, so the prompt is part of
 *  the surface rather than buried in settings. */
function FramePicker({ profile, onSet }) {
  const [countries, setCountries] = useState([]);
  useEffect(() => { fetchCountries().then((d) => setCountries(d.countries || [])).catch(() => {}); }, []);
  const current = profile?.country || "";
  return (
    <div className={`rd-frame ${current ? "" : "unset"}`}>
      <Icon name="compass" size={15} />
      <span>{current ? "Reading from" : "Where are you reading from?"}</span>
      <select value={current} onChange={(e) => onSet(e.target.value)}>
        <option value="">choose a country…</option>
        {countries.map((c) => <option key={c.country} value={c.country}>{c.name}</option>)}
      </select>
      {!current && <span className="rd-frame-why">The same event means different things in different places.</span>}
    </div>
  );
}

const FILTERS = [
  { k: "all", label: "All", test: () => true },
  { k: "confident", label: "Confident", test: (c) => c.confidence >= 0.7 },
  { k: "disputed", label: "Disputed", test: (c) => c.contradicts?.length > 0 },
  { k: "short", label: "Days or less", test: (c) => ["hours", "days"].includes(c.horizon) },
];

export function RadarView({ user, onLogin }) {
  const [d, setD] = useState(undefined);
  const [filter, setFilter] = useState("all");
  const [category, setCategory] = useState("");

  const load = () => { setD(undefined); fetchClaims({ hours: 336 }).then(setD).catch(() => setD(null)); };
  useEffect(load, [user]);

  const setFrame = async (country) => {
    if (!country) return;
    await saveProfileFrame({ country });
    load();
  };

  const claims = d?.claims || [];
  const categories = useMemo(
    () => [...new Set(claims.map((c) => c.category).filter(Boolean))].sort(), [claims]);

  if (d === null) return <LoadError what="the radar" onRetry={load} />;

  const active = FILTERS.find((f) => f.k === filter) || FILTERS[0];
  const shown = claims.filter((c) => active.test(c) && (!category || c.category === category));

  return (
    <div>
      <div className="page-head">
        <div>
          <h1 className="page-title">Radar</h1>
          <p className="page-sub">
            What happened, and what it means for you — ranked by how much it touches your world.
          </p>
        </div>
      </div>

      {user
        ? <FramePicker profile={d?.profile} onSet={setFrame} />
        : (
          <div className="rd-frame unset">
            <Icon name="compass" size={15} />
            <span>This feed is ranked generically.</span>
            <button className="act" onClick={onLogin}>Log in to make it yours</button>
          </div>
        )}

      {claims.length > 0 && (
        <div className="j-tabs" style={{ marginTop: 14 }}>
          {FILTERS.map((f) => (
            <button key={f.k} className={`j-tab ${filter === f.k ? "on" : ""}`} onClick={() => setFilter(f.k)}>
              {f.label} <span className="j-tab-n">{claims.filter(f.test).length}</span>
            </button>
          ))}
          {categories.length > 1 && (
            <select className="rd-cat-filter" value={category} onChange={(e) => setCategory(e.target.value)}>
              <option value="">every category</option>
              {categories.map((c) => <option key={c} value={c}>{c.replace(/_/g, " ")}</option>)}
            </select>
          )}
        </div>
      )}

      {d === undefined ? (
        [0, 1, 2].map((i) => <div key={i} className="rd-card"><div className="skel" style={{ width: `${80 - i * 12}%` }} /></div>)
      ) : claims.length === 0 ? (
        <EmptyState title="Nothing interpreted yet">
          The engine reads incoming events and writes an interpretation when it can identify a
          specific causal mechanism. It deliberately writes nothing when it cannot — a vague call
          would still be scored in the Ledger, so inventing one would corrupt the track record.
          Interpretations appear here as events arrive.
        </EmptyState>
      ) : shown.length === 0 ? (
        <EmptyState title="Nothing in this view">Try a different filter.</EmptyState>
      ) : (
        shown.map((c) => <Card key={c.id} c={c} />)
      )}

      {claims.length > 0 && <div className="disc" style={{ marginTop: 16 }}>{d.disclaimer}</div>}
    </div>
  );
}
