#!/usr/bin/env bash
#
# One command between `git clone` and a running instance.
#
# It exists because hardening the database password made the quickstart longer: `docker-compose.yml`
# no longer carries `POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}`, so the stack refuses to start until .env has a
# real one. Asking a stranger to invent a password by hand is how a ten-minute quickstart becomes a
# twenty-minute one, and how "tradeos" ends up typed in anyway.
#
# Everything it writes is either generated on this machine or copied from .env.example. It never
# contacts the network, never overwrites an existing .env, and never prints a secret.
set -euo pipefail

cd "$(dirname "$0")/.."

ENV_FILE=".env"
TEMPLATE=".env.example"

if [ -f "$ENV_FILE" ]; then
  echo "$ENV_FILE already exists — leaving it alone."
  echo "If the stack will not start, check that POSTGRES_PASSWORD is set in it."
  exit 0
fi

[ -f "$TEMPLATE" ] || { echo "error: $TEMPLATE is missing; are you in the repository root?" >&2; exit 1; }

# 32 hex characters from the OS CSPRNG. Hex rather than base64 so the value is safe unquoted in a
# URL, a compose file and a psql connection string — a `/` or `+` in a password inside
# postgresql://user:pass@host breaks the parse, and that failure reads as "the database is down".
generate_password() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 16
  else
    # Python is a hard dependency of this project, so this is a fallback that always exists.
    python3 -c 'import secrets; print(secrets.token_hex(16))'
  fi
}

cp "$TEMPLATE" "$ENV_FILE"
PW="$(generate_password)"

# Append rather than sed the template: the template documents POSTGRES_PASSWORD as a comment, and a
# later duplicate wins in docker compose's .env parsing. Appending keeps the explanation visible
# above the generated line instead of replacing it with an opaque value.
cat >> "$ENV_FILE" <<EOF

# ---- generated by scripts/setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ) ------------------------
# The database password for the local Postgres container. Generated on this machine; never shared,
# never committed (.env is gitignored). If you delete the pgdata volume, this can be regenerated;
# if you keep the volume, changing this value will lock you out of your own database, because
# Postgres only reads it when the cluster is first initialised.
POSTGRES_PASSWORD=$PW
EOF

chmod 600 "$ENV_FILE"

echo "Wrote $ENV_FILE with a generated database password (not shown)."
echo
echo "ONE thing left, and it is the only external key this product needs:"
echo
echo "  1. Get a free Alpaca key — no card — at https://app.alpaca.markets/signup"
echo "     Then: the paper-trading dashboard, 'API Keys', 'Generate'."
echo "  2. Put BOTH halves in $ENV_FILE:"
echo "         ALPACA_API_KEY_ID=..."
echo "         ALPACA_API_SECRET_KEY=..."
echo "  3. make quickstart"
echo
echo "That brings the stack up, migrates, and loads a year of daily closes for 400 symbols"
echo "(about 20 seconds) so you can publish a call straight away."
echo
echo "If prices do not appear, 'docker compose exec -T api python -m tradeos.cli check-source alpaca'"
echo "makes a real request and says which half of the credential is wrong."
